/**
 * Dev Team Plugin — federation entry point
 *
 * This file is not the federation remote entry (that's auto-generated by vite-plugin-federation).
 * It's just a placeholder / re-export for any future plugin-level setup.
 *
 * The actual exposed module is TicketsView.vue, configured in vite.config.ts.
 */
export { default as TicketsView } from './TicketsView.vue'
